scilone_pass_manager_account_homepage:
    path:     /
    defaults: { _controller: ScilonePassManagerBundle:Account:index }

scilone_pass_manager_account_new:
    path:     /account/new
    defaults: { _controller: ScilonePassManagerBundle:Account:add }

scilone_pass_manager_account_xhr_modal_right:
    path:     /xhr/account/modal/right/{idAccount}
    defaults: { _controller: ScilonePassManagerBundle:Account:xhrModalRight }
    options:
        expose: true