<?php

namespace Scilone\AclBundle\Repository;

/**
 * AclRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
