scilone_acl:
    resource: "@SciloneAclBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

scilone_generator:
    resource: "@SciloneGeneratorBundle/Resources/config/routing.yml"
    prefix:   /

scilone_encryption:
    resource: "@SciloneEncryptionBundle/Resources/config/routing.yml"
    prefix:   /

scilone_pass_manager:
    resource: "@ScilonePassManagerBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
