<?php

namespace Scilone\EncryptionBundle\Repository;

/**
 * MasterKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
