<?php

namespace Scilone\EncryptionBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * MasterKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterKeyRepository extends EntityRepository
{
}
